# Generated by Django 3.1.1 on 2020-09-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenBondApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='project',
            new_name='projects',
        ),
    ]
