# Generated by Django 3.1.1 on 2020-10-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenBondApp', '0003_auto_20201001_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sdg',
            new_name='sdgs',
        ),
    ]
